DROP DATABASE surenPrinters;
CREATE DATABASE IF NOT EXISTS surenPrinters;
USE surenPrinters;
DROP TABLE IF EXISTS Companies CASCADE;
CREATE TABLE Companies(
    ID int NOT NULL AUTO_INCREMENT,
    CompanyName VARCHAR(1000) NOT NULL,
    Address VARCHAR(1000) NOT NULL,
    PRIMARY KEY(ID)
);
DROP TABLE IF EXISTS Bills CASCADE;
CREATE TABLE Bills(
    ID int NOT NULL AUTO_INCREMENT,
    CompanyID int NOT NULL,
    PayStatus int NOT NULL DEFAULT 0,
    BillDate VARCHAR(255),
    PRIMARY KEY(ID),
    FOREIGN KEY(CompanyID) REFERENCES Companies(ID)
);
DROP TABLE IF EXISTS Items CASCADE;
CREATE TABLE Items(
    ID int NOT NULL AUTO_INCREMENT,
    BillID int NOT NULL,
    Name VARCHAR(1000),
    Quantity int,
    Price int,
    PRIMARY KEY(ID),
    FOREIGN KEY(BillID) REFERENCES Bills(ID)
);